# Revisión

* ¿Debemos explorar las relaciones entre nuestras variables?
* 
* ¿Por qué usamos el paquete `edgeR`?
* ¿Por qué es importante el argumento `sort.by` en `topTable()`?
* ¿Por qué es importante el argumento `coef` en `topTable()`?

# spatialLIBD

<script async class="speakerdeck-embed" data-id="329db23f5f17460da31f45c7695a9f06" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>

* Artículo: https://www.nature.com/articles/s41593-020-00787-0
* Software: http://research.libd.org/spatialLIBD/
* Interfaz de shiny: http://spatial.libd.org/spatialLIBD/

Brenda Pardo

https://twitter.com/PardoBree

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Today I gave my first talk at a congress in <a href="https://twitter.com/hashtag/EuroBioc2020?src=hash&amp;ref_src=twsrc%5Etfw">#EuroBioc2020</a> about our work on adapting the package <a href="https://twitter.com/hashtag/spatialLIBD?src=hash&amp;ref_src=twsrc%5Etfw">#spatialLIBD</a> to use VisiumExperiment objects. <a href="https://t.co/U23yE32RWM">pic.twitter.com/U23yE32RWM</a></p>&mdash; Brenda Pardo (@PardoBree) <a href="https://twitter.com/PardoBree/status/1338560370382942209?ref_src=twsrc%5Etfw">December 14, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Comunidad

* https://twitter.com/miR_community
* https://twitter.com/R_LGBTQ
* https://twitter.com/conecta_R
* https://twitter.com/LatinR_Conf
* https://twitter.com/R4DScommunity
* https://twitter.com/RConsortium
* https://twitter.com/rweekly_org
* https://twitter.com/RLadiesGlobal
* https://twitter.com/RLadiesBmore
* https://twitter.com/search?q=%23RLadiesMX&src=typed_query

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The blog post about the First annual meeting of <a href="https://twitter.com/hashtag/RLadiesMX?src=hash&amp;ref_src=twsrc%5Etfw">#RLadiesMX</a> is ready!! All <a href="https://twitter.com/hashtag/rladies?src=hash&amp;ref_src=twsrc%5Etfw">#rladies</a> chapters in México met for the first time! 🤩 Spread the word and join this amazing community 💜<a href="https://t.co/evY4Tc18rw">https://t.co/evY4Tc18rw</a> Thanks <a href="https://twitter.com/AnaBetty2304?ref_src=twsrc%5Etfw">@AnaBetty2304</a> <a href="https://twitter.com/Averi_GG?ref_src=twsrc%5Etfw">@Averi_GG</a> and <a href="https://twitter.com/josschavezf1?ref_src=twsrc%5Etfw">@josschavezf1</a> for all your work!</p>&mdash; RLadies Cuernavaca (@RLadiesCuerna) <a href="https://twitter.com/RLadiesCuerna/status/1355655180751151107?ref_src=twsrc%5Etfw">January 30, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

* https://twitter.com/Bioconductor
* https://twitter.com/rOpenSci
* https://twitter.com/LIBDrstats
* https://twitter.com/CDSBMexico

<blockquote class="twitter-tweet"><p lang="es" dir="ltr">¡Chequen el nuevo blog post de Erick <a href="https://twitter.com/ErickCuevasF?ref_src=twsrc%5Etfw">@ErickCuevasF</a>! 💯<br><br>Nos describe sus experiencias en <a href="https://twitter.com/hashtag/BioC2020?src=hash&amp;ref_src=twsrc%5Etfw">#BioC2020</a> y <a href="https://twitter.com/hashtag/CDSB2020?src=hash&amp;ref_src=twsrc%5Etfw">#CDSB2020</a><br><br>Además estamos orgullxs de que Erick se unió a la Junta Directiva de la CDSB 🤩🎉<br><br>👀 <a href="https://t.co/uGpgnqXvVM">https://t.co/uGpgnqXvVM</a><a href="https://twitter.com/hashtag/rstatsES?src=hash&amp;ref_src=twsrc%5Etfw">#rstatsES</a> <a href="https://t.co/O2eIbk5YoZ">pic.twitter.com/O2eIbk5YoZ</a></p>&mdash; ComunidadBioInfo (@CDSBMexico) <a href="https://twitter.com/CDSBMexico/status/1296920807105540098?ref_src=twsrc%5Etfw">August 21, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## De ustedes

<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://twitter.com/fikandata?ref_src=twsrc%5Etfw">@fikandata</a> <a href="https://twitter.com/MqElizabeth?ref_src=twsrc%5Etfw">@MqElizabeth</a> <br><br>Looking for a solid and useful R 📦, we stumbled upon this <br>beauty 🤩 <a href="https://t.co/KR3twAxqRY">https://t.co/KR3twAxqRY</a><br><br>shoutouts to <a href="https://twitter.com/digitalwright?ref_src=twsrc%5Etfw">@digitalwright</a> 👈!!<a href="https://twitter.com/lcolladotor?ref_src=twsrc%5Etfw">@lcolladotor</a> <a href="https://twitter.com/Bioconductor?ref_src=twsrc%5Etfw">@Bioconductor</a></p>&mdash; Axel Zagal Norman (@NormanZagal) <a href="https://twitter.com/NormanZagal/status/1364381133878611968?ref_src=twsrc%5Etfw">February 24, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">In today&#39;s lesson of bioinformatics course of undergraduate program in genomic sciences <a href="https://twitter.com/lcgunam?ref_src=twsrc%5Etfw">@lcgunam</a> we created our first personal page using <a href="https://twitter.com/seankross?ref_src=twsrc%5Etfw">@seankross</a>&#39; postcards R package with <a href="https://twitter.com/lcolladotor?ref_src=twsrc%5Etfw">@lcolladotor</a> as our instructor. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/sXUSietCZy">https://t.co/sXUSietCZy</a></p>&mdash; Angel Castillo (@angelcaztle13) <a href="https://twitter.com/angelcaztle13/status/1364466027682140162?ref_src=twsrc%5Etfw">February 24, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Wake up <br>Brew some <a href="https://twitter.com/tyulmalcafe?ref_src=twsrc%5Etfw">@tyulmalcafe</a> beans <br>Attend <a href="https://twitter.com/lcolladotor?ref_src=twsrc%5Etfw">@lcolladotor</a> amazing class on visualizing expression data using ISEE <a href="https://twitter.com/FedeBioinfo?ref_src=twsrc%5Etfw">@FedeBioinfo</a> <a href="https://twitter.com/KevinRUE67?ref_src=twsrc%5Etfw">@KevinRUE67</a> <a href="https://twitter.com/CSoneson?ref_src=twsrc%5Etfw">@CSoneson</a> <br>Am I dreaming? <br>Nah! Mug is empty.</p>&mdash; Alfredo Varela (@fikandata) <a href="https://twitter.com/fikandata/status/1364669473634983941?ref_src=twsrc%5Etfw">February 24, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

